import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'

//  Components
import Navbar from '../components/Navbar/index';
import Hero from '../components/Hero/index';
import {Container, Box} from '@chakra-ui/react';

export default function Home() {
  return (
    <Box sx={styles.container} width='100%' height='100%'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet"/>
      </Head>
      <Navbar/>
      <Hero/>
    </Box>
  )
}


const styles = {
  container: {
    overflowX: 'hidden',
    backgroundImage: 'url(./bg.png)',
    height: '100%',
    backgroundPosition: 'center',
    backgroundRepeat: 'no-repeat',
    backgroundSize: 'cover',
    backgroundAttachment: 'fixed'
  }
}